joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
  
camera_controller:
  type: "position_controllers/JointPositionController"
  joint: base_to_camera

right_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: wheelright

left_wheel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: wheelleft
